# commented are part of the API but not yet implemented
# export SPACE_LOG_ENABLED=
# export SPACE_WORKQUEUE_MONGO_URL=
# export SPACE_WORKQUEUE_MONGO_OPLOG_URL=
# export SPACE_WORKQUEUE_COLLECTION_NAME=
# export SPACE_ES_LOG_ENABLED=
export SPACE_ES_COMMITS_MONGO_URL=
export SPACE_ES_COMMITS_MONGO_OPLOG_URL=
export SPACE_ES_COMMITS_COLLECTION_NAME=
#export SPACE_ES_COMMITS_PROCESSING_TIMEOUT=
export SPACE_ES_SNAPSHOTTING_ENABLED=
export SPACE_ES_SNAPSHOTTING_FREQUENCY=
export SPACE_ES_SNAPSHOTTING_COLLECTION_NAME=
